### PR TITLE
Add jq and curl

### PR DESCRIPTION
**Pull request by mogul**
## Changes proposed in this pull request:

- add jq and curl CLI utils (seems like their absence might be a problem)

## Security considerations

None, these are well-understood CLI utilities that are being pulled from the upstream Alpine repository, which is updated frequently.

### CODE REVIEW

**Comment by markdboyd** [comment]
Why does this CLI image need those utilities? How would people use them in an actual CI workflow?

**Comment by mogul** [comment]
The action is also useful for running more complex scripts that assume the caller is already authenticated with cloud.gov and pointing to the appropriate space. Here's an [example workflow](https://github.com/GSA-TTS/FAC/blob/41245909dc3b43d4b7a9bc49a4b50ae26a92f254/.github/workflows/deploy-application.yml#L92-L101) and [the script it points to](https://github.com/GSA-TTS/FAC/blob/main/bin/ops/deploy.sh). In this case the script is mainly using `cf curl` but you can imagine another one that needs to download a file or reference the result of a request during deployment. For those very simple needs, `curl` and `jq` will do.

**Comment by FuhuXia** [comment]
I would also like to add `grep` into the list as in
```
apk add --no-cache bash jq curl grep
```
We have [a workflow step](https://github.com/GSA/catalog.data.gov/blob/22670d00f510687e9427b2677e99d73b3b401d49/.github/workflows/ckan.yml#L73-L78) to monitor the output of a cf command, in which [a script](https://github.com/GSA/catalog.data.gov/blob/22670d00f510687e9427b2677e99d73b3b401d49//tools/monitor_cf_logs.sh#L17) is relying on grep's `--line-buffered` option. The BusyBox `grep` that comes with Alpine version does not support this option. We have to install it in our run script after getting `cloud-gov/cg-cli-tools`. But installing a GNU grep here, not in our script [as done here](https://github.com/GSA/catalog.data.gov/pull/1156/files),   is considered better for anyone like our team using `grep`.

Is it possible to add `grep` when merging this PR? @mogul @markdboyd

**Comment by mogul** [comment]
I'm okay with that; @markdboyd ...?

Also if there's a common pack of binutil-type stuff not covered by BusyBox, let's just go ahead and install it.

(And: Sorry for the breaking change, @FuhuXia !)

**Comment by mogul** [comment]
For example:
https://wiki.alpinelinux.org/wiki/How_to_get_regular_stuff_working

**Comment by markdboyd** [comment]
@mogul sure, feel free to add `grep`

**Review by markdboyd — APPROVED** [review]

**Comment by markdboyd** [comment]
@FuhuXia @mogul I just decided to create a separate PR for including `grep`: #24

**Pull request merged**
